[project]
name = "vec-current-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "homeassistant>=2025.4.4",
    "websockets>=15.0.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.8",
]
